Check all dist folders are up to date

diff --git a/.github/workflows/zz-build-and-test.yml b/.github/workflows/zz-build-and-test.yml
--- a/.github/workflows/zz-build-and-test.yml
+++ b/.github/workflows/zz-build-and-test.yml
@@ -27,8 +27,8 @@ jobs:
         run: yarn build
       - name: Check dist is up to date
         run: |
-          git diff --exit-code migrations/deploy/dist/ || (
-            echo "Error: dist/ is out of date. Run 'yarn build' and commit the changes."
+          git diff --exit-code '**/dist/' || (
+            echo "Error: build is out of date. Run 'yarn build' and commit the changes."
             exit 1
           )
 
